### ISSUE TITLE
FeatureStoreRedis shouldn't use Redis KEYS command

### ISSUE THREAD

**Issue by kutzi** [clun/ff4j#177] opened 2017-01-06 14:30 UTC
As mentioned on several places (e.g. https://redis.io/commands/KEYS) you shouldn't ever run KEYS on production instances as it is blocking and potentially very slow.

**Comment by kutzi** [comment] 2017-01-06 14:31
BTW: we have fixed it by using scan like this:

```
  private Set<String> allKeys() {
    Set<String> myKeys = new TreeSet<>();

    ScanParams match = new ScanParams().match(KEY_FEATURE + "*");
    try (Jedis jedis = getJedis()) {
      ScanResult<String> scan;
      String cursor = ScanParams.SCAN_POINTER_START;
      do {
        scan = jedis.scan(cursor, match);
        cursor = scan.getStringCursor();
        myKeys.addAll(scan.getResult());
      } while(!ScanParams.SCAN_POINTER_START.equals(cursor));
    }

    return myKeys;
  }
```

**Comment by kutzi** [comment] 2017-01-06 14:41
(It's very annoying that the bounty-source-plugin is rewriting comments!)

**Comment by clun** [comment] 2017-01-07 20:48
Thank you, will update the store regarding your comment. And disable this f*** bounty source => useless.

**Comment by kutzi** [comment] 2017-01-08 12:23
Thanks.
Additional observations, thoughts:
While debugging this I saw that keys() was actually called 3 times when opening the FF4J console:
  for the feature store, for the groups and for the property store
I think at the least the 1st 2 could be collapsed to one call

Even after changing it to scan the overall complexity of a complete scan iteration is O(n) - which can mean up to several seconds on big Redis DBs
So you might want to thing about a more efficient way of storing the features in Redis.
Maybe hashsets or so

**Comment by clun** [comment] 2017-01-08 18:34
BountySource disabled for good.
Good catch. On the contrary performing a "GET" is only O(log(n)) right ?

So what about structure:
```
key=FF4J_FEATURENAMES, value=sortedSet with all keys for features id
key=FF4J_GROUPNAMES, value=sortedSet with all keys for groupName
key=FF4J_GROUP_GROUPID, value=sortedset with all keys for feature and this group
```
They will act as "directory" to find others components. To get all features I would have 
Complexity of get all features : 1 + nbFeatures * log(N) 

There will be a lot of get/set but no scanning.

What do you think ?

**Comment by kutzi** [comment] 2017-01-08 18:44
I thought initially about storing the complete features in one HASH, and if you need all of them to just call HGETALL. That would be much more to change, but in the end maybe less complicated to use, because you don't have to maintain a 3 additional dictionaries for names, groups and mappings.

But not sure, yet, if I understood your structure completely

**Comment by kutzi** [comment] 2017-01-09 14:39
FWIW, after changing to the SCAN approach opening the FF4J console now takes several minutes for us (keyspace of ~2.5mio keys). So you should maybe immediately start with the refactoring instead of going with the SCAN approach.

We're currently experimenting with different COUNT values to see if we can speed up the scan.

**Comment by kutzi** [comment] 2017-01-09 15:39
FYI: in ConsoleRenderer readAllGroups() is called twice in succession - which is totally unnecessary.
You should IMO fix it ASAP as it is an easy fix.

See https://github.com/clun/ff4j/blob/c0593eac99e6615ecc253bc21d91fb33ef920d23/ff4j-web/src/main/java/org/ff4j/web/embedded/ConsoleRenderer.java#L546

**Comment by clun** [comment] 2017-01-14 10:26
Crap!, just review this comment. 

Well this fix will be in 1.6.2 (I set up my new laptop releases should be easier to me). Let me know if you can display the console in 1.6.1 as expected (it will be available in a couple of hours : time for sonatype to upload to central).

**Comment by kutzi** [comment] 2017-01-14 10:34
With this new Console Servlet that changes all again, I think - the code path from above is not used anymore. But this readAll() is called multiple times (readAllGroups() calls realAll(), too)

Our 'fix' is currently to put a cache decorator around the RedisFeatureStore to cache readAll() for a couple of minutes and also calculate the result of readAllGroups() from the cached readAll() result

**Comment by kutzi** [comment] 2017-01-14 10:34
As a general solution you should IMHO still think about reworking the data model for the Redis store

**Comment by clun** [comment] 2017-01-14 11:18
Agreed. But not for 1.x a think. The issue is still open. 

Let me come up with something. Your design with single key is good but I don't know if unmarshalling cost much than multi access to redis (which very fast). 

You can also think about in memory near cache enabled (ehcache, jcache) for the "check".

**Comment by clun** [comment] 2017-04-27 07:20
Improvements by add a MAP as dictionnary to access features, real performance improvement, will be part of 1.6.4

**Comment by clun** [comment] 2017-05-01 00:14
Part of 1.6.4 released 2017_05_01

**Closed by clun** 2017-05-01 00:14 UTC
Labels: ready-for-release, v1.6.x
